// lib/geoData.js

// District List
export const districts = [
  "Dhaka",
  "Gazipur",
  "Narayanganj",
  "Narsingdi",
  "Tangail",
  "Kishoreganj",
  "Faridpur",
  "Gopalganj",
  "Madaripur",
  "Rajbari",
  "Shariatpur",
  "Manikganj",
  "Munshiganj",

  "Chattogram",
  "Cox's Bazar",
  "Cumilla",
  "Brahmanbaria",
  "Chandpur",
  "Feni",
  "Lakshmipur",
  "Noakhali",
  "Khagrachhari",
  "Rangamati",
  "Bandarban",

  "Rajshahi",
  "Bogura",
  "Pabna",
  "Sirajganj",
  "Naogaon",
  "Natore",
  "Joypurhat",
  "Chapainawabganj",

  "Khulna",
  "Jashore",
  "Satkhira",
  "Bagerhat",
  "Narail",
  "Magura",
  "Jhenaidah",
  "Chuadanga",
  "Kushtia",
  "Meherpur",

  "Barishal",
  "Bhola",
  "Patuakhali",
  "Pirojpur",
  "Jhalokathi",
  "Barguna",

  "Sylhet",
  "Moulvibazar",
  "Habiganj",
  "Sunamganj",

  "Rangpur",
  "Dinajpur",
  "Nilphamari",
  "Panchagarh",
  "Thakurgaon",
  "Lalmonirhat",
  "Kurigram",
  "Gaibandha",

  "Mymensingh",
  "Jamalpur",
  "Netrokona",
  "Sherpur",
];

// Upazilas By District
export const upazilas = {
  Dhaka: ["Dhamrai", "Dohar", "Keraniganj", "Nawabganj", "Savar"],

  Gazipur: ["Gazipur Sadar", "Kaliakair", "Kaliganj", "Kapasia", "Sreepur"],

  Narayanganj: [
    "Araihazar",
    "Bandar",
    "Narayanganj Sadar",
    "Rupganj",
    "Sonargaon",
  ],

  Narsingdi: [
    "Narsingdi Sadar",
    "Belabo",
    "Monohardi",
    "Palash",
    "Raipura",
    "Shibpur",
  ],

  Tangail: [
    "Tangail Sadar",
    "Basail",
    "Bhuapur",
    "Delduar",
    "Dhanbari",
    "Ghatail",
    "Gopalpur",
    "Kalihati",
    "Madhupur",
    "Mirzapur",
    "Nagarpur",
    "Sakhipur",
  ],

  Kishoreganj: [
    "Kishoreganj Sadar",
    "Astagram",
    "Bajitpur",
    "Bhairab",
    "Hossainpur",
    "Itna",
    "Karimganj",
    "Katiadi",
    "Kuliarchar",
    "Mithamain",
    "Nikli",
    "Pakundia",
    "Tarail",
  ],

  Faridpur: [
    "Faridpur Sadar",
    "Alfadanga",
    "Bhanga",
    "Boalmari",
    "Charbhadrasan",
    "Madhukhali",
    "Nagarkanda",
    "Sadarpur",
    "Saltha",
  ],

  Gopalganj: [
    "Gopalganj Sadar",
    "Kashiani",
    "Kotalipara",
    "Muksudpur",
    "Tungipara",
  ],

  Madaripur: ["Madaripur Sadar", "Kalkini", "Rajoir", "Shibchar"],

  Rajbari: [
    "Rajbari Sadar",
    "Baliakandi",
    "Goalandaghat",
    "Kalukhali",
    "Pangsha",
  ],

  Shariatpur: [
    "Shariatpur Sadar",
    "Bhedarganj",
    "Damudya",
    "Gosairhat",
    "Naria",
    "Zajira",
  ],

  Manikganj: [
    "Manikganj Sadar",
    "Daulatpur",
    "Gheor",
    "Harirampur",
    "Saturia",
    "Shibalaya",
    "Singair",
  ],

  Munshiganj: [
    "Munshiganj Sadar",
    "Gajaria",
    "Louhajang",
    "Sirajdikhan",
    "Sreenagar",
    "Tongibari",
  ],

  Chattogram: [
    "Anwara",
    "Banshkhali",
    "Boalkhali",
    "Chandanaish",
    "Fatikchhari",
    "Hathazari",
    "Karnafuli",
    "Lohagara",
    "Mirsharai",
    "Patiya",
    "Rangunia",
    "Raozan",
    "Sandwip",
    "Satkania",
    "Sitakunda",
  ],

  "Cox's Bazar": [
    "Cox's Bazar Sadar",
    "Chakaria",
    "Eidgaon",
    "Kutubdia",
    "Maheshkhali",
    "Pekua",
    "Ramu",
    "Teknaf",
    "Ukhia",
  ],

  Cumilla: [
    "Cumilla Sadar",
    "Cumilla Sadar Dakshin",
    "Barura",
    "Brahmanpara",
    "Burichang",
    "Chandina",
    "Chauddagram",
    "Daudkandi",
    "Debidwar",
    "Homna",
    "Laksam",
    "Lalmai",
    "Meghna",
    "Monohargonj",
    "Muradnagar",
    "Nangalkot",
    "Titas",
  ],

  Brahmanbaria: [
    "Brahmanbaria Sadar",
    "Akhaura",
    "Ashuganj",
    "Bancharampur",
    "Bijoynagar",
    "Kasba",
    "Nabinagar",
    "Nasirnagar",
    "Sarail",
  ],

  Chandpur: [
    "Chandpur Sadar",
    "Faridganj",
    "Haimchar",
    "Hajiganj",
    "Kachua",
    "Matlab Dakshin",
    "Matlab Uttar",
    "Shahrasti",
  ],

  Feni: [
    "Feni Sadar",
    "Chhagalnaiya",
    "Daganbhuiyan",
    "Fulgazi",
    "Parshuram",
    "Sonagazi",
  ],

  Lakshmipur: [
    "Lakshmipur Sadar",
    "Kamalnagar",
    "Raipur",
    "Ramganj",
    "Ramgati",
  ],

  Noakhali: [
    "Noakhali Sadar",
    "Begumganj",
    "Chatkhil",
    "Companiganj",
    "Hatiya",
    "Kabirhat",
    "Senbagh",
    "Sonaimuri",
    "Subarnachar",
  ],

  Khagrachhari: [
    "Khagrachhari Sadar",
    "Dighinala",
    "Guimara",
    "Lakshmichhari",
    "Mahalchhari",
    "Manikchhari",
    "Matiranga",
    "Panchhari",
    "Ramgarh",
  ],

  Rangamati: [
    "Rangamati Sadar",
    "Bagaichhari",
    "Barkal",
    "Belaichhari",
    "Juraichhari",
    "Kaptai",
    "Kawkhali",
    "Langadu",
    "Naniarchar",
    "Rajasthali",
  ],

  Bandarban: [
    "Bandarban Sadar",
    "Ali Kadam",
    "Lama",
    "Naikhongchhari",
    "Rowangchhari",
    "Ruma",
    "Thanchi",
  ],

  Rajshahi: [
    "Paba",
    "Bagha",
    "Bagmara",
    "Charghat",
    "Durgapur",
    "Godagari",
    "Mohanpur",
    "Puthia",
    "Tanore",
  ],

  Bogura: [
    "Bogura Sadar",
    "Adamdighi",
    "Dhunat",
    "Dhupchanchia",
    "Gabtali",
    "Kahaloo",
    "Nandigram",
    "Sariakandi",
    "Shajahanpur",
    "Sherpur",
    "Shibganj",
    "Sonatala",
  ],

  Pabna: [
    "Pabna Sadar",
    "Atgharia",
    "Bera",
    "Bhangura",
    "Chatmohar",
    "Faridpur",
    "Ishwardi",
    "Santhia",
    "Sujanagar",
  ],

  Sirajganj: [
    "Sirajganj Sadar",
    "Belkuchi",
    "Chauhali",
    "Kamarkhanda",
    "Kazipur",
    "Raiganj",
    "Shahjadpur",
    "Tarash",
    "Ullahpara",
  ],

  Naogaon: [
    "Naogaon Sadar",
    "Atrai",
    "Badalgachhi",
    "Dhamoirhat",
    "Mahadevpur",
    "Manda",
    "Niamatpur",
    "Patnitala",
    "Porsha",
    "Raninagar",
    "Sapahar",
  ],

  Natore: [
    "Natore Sadar",
    "Bagatipara",
    "Baraigram",
    "Gurudaspur",
    "Lalpur",
    "Naldanga",
    "Singra",
  ],

  Joypurhat: ["Joypurhat Sadar", "Akkelpur", "Kalai", "Khetlal", "Panchbibi"],

  Chapainawabganj: [
    "Chapainawabganj Sadar",
    "Bholahat",
    "Gomastapur",
    "Nachole",
    "Shibganj",
  ],

  Khulna: [
    "Batiaghata",
    "Dacope",
    "Dighalia",
    "Dumuria",
    "Koyra",
    "Paikgachha",
    "Phultala",
    "Rupsha",
    "Terokhada",
  ],

  Jashore: [
    "Jashore Sadar",
    "Abhaynagar",
    "Bagherpara",
    "Chougachha",
    "Jhikargachha",
    "Keshabpur",
    "Manirampur",
    "Sharsha",
  ],

  Satkhira: [
    "Satkhira Sadar",
    "Assasuni",
    "Debhata",
    "Kalaroa",
    "Kaliganj",
    "Shyamnagar",
    "Tala",
  ],

  Bagerhat: [
    "Bagerhat Sadar",
    "Chitalmari",
    "Fakirhat",
    "Kachua",
    "Mollahat",
    "Mongla",
    "Morrelganj",
    "Rampal",
    "Sarankhola",
  ],

  Narail: ["Narail Sadar", "Kalia", "Lohagara"],

  Magura: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],

  Jhenaidah: [
    "Jhenaidah Sadar",
    "Harinakunda",
    "Kaliganj",
    "Kotchandpur",
    "Maheshpur",
    "Shailkupa",
  ],

  Chuadanga: ["Chuadanga Sadar", "Alamdanga", "Damurhuda", "Jibannagar"],

  Kushtia: [
    "Kushtia Sadar",
    "Bheramara",
    "Daulatpur",
    "Khoksa",
    "Kumarkhali",
    "Mirpur",
  ],

  Meherpur: ["Meherpur Sadar", "Gangni", "Mujibnagar"],

  Barishal: [
    "Barishal Sadar",
    "Agailjhara",
    "Babuganj",
    "Bakerganj",
    "Banaripara",
    "Gournadi",
    "Hizla",
    "Mehendiganj",
    "Muladi",
    "Wazirpur",
  ],

  Bhola: [
    "Bhola Sadar",
    "Burhanuddin",
    "Char Fasson",
    "Daulatkhan",
    "Lalmohan",
    "Manpura",
    "Tazumuddin",
  ],

  Patuakhali: [
    "Patuakhali Sadar",
    "Bauphal",
    "Dashmina",
    "Dumki",
    "Galachipa",
    "Kalapara",
    "Mirzaganj",
    "Rangabali",
  ],

  Pirojpur: [
    "Pirojpur Sadar",
    "Bhandaria",
    "Indurkani",
    "Kawkhali",
    "Mathbaria",
    "Nazirpur",
    "Nesarabad",
  ],

  Jhalokathi: ["Jhalokathi Sadar", "Kathalia", "Nalchity", "Rajapur"],

  Barguna: [
    "Barguna Sadar",
    "Amtali",
    "Bamna",
    "Betagi",
    "Patharghata",
    "Taltali",
  ],

  Sylhet: [
    "Sylhet Sadar",
    "Balaganj",
    "Beanibazar",
    "Bishwanath",
    "Companiganj",
    "Fenchuganj",
    "Golapganj",
    "Gowainghat",
    "Jaintiapur",
    "Kanaighat",
    "Osmani Nagar",
    "South Surma",
    "Zakiganj",
  ],

  Moulvibazar: [
    "Moulvibazar Sadar",
    "Barlekha",
    "Juri",
    "Kamalganj",
    "Kulaura",
    "Rajnagar",
    "Sreemangal",
  ],

  Habiganj: [
    "Habiganj Sadar",
    "Ajmiriganj",
    "Bahubal",
    "Baniachong",
    "Chunarughat",
    "Lakhai",
    "Madhabpur",
    "Nabiganj",
    "Shayestaganj",
  ],

  Sunamganj: [
    "Sunamganj Sadar",
    "Bishwambarpur",
    "Chhatak",
    "Derai",
    "Dowarabazar",
    "Jagannathpur",
    "Jamalganj",
    "Shantiganj",
    "Sullah",
    "Tahirpur",
  ],

  Rangpur: [
    "Rangpur Sadar",
    "Badarganj",
    "Gangachara",
    "Kaunia",
    "Mithapukur",
    "Pirgachha",
    "Pirganj",
    "Taraganj",
  ],

  Dinajpur: [
    "Dinajpur Sadar",
    "Birol",
    "Birampur",
    "Birganj",
    "Bochaganj",
    "Chirirbandar",
    "Ghoraghat",
    "Hakimpur",
    "Kaharole",
    "Khansama",
    "Nawabganj",
    "Parbatipur",
    "Phulbari",
  ],

  Nilphamari: [
    "Nilphamari Sadar",
    "Dimla",
    "Domar",
    "Jaldhaka",
    "Kishoreganj",
    "Saidpur",
  ],

  Panchagarh: ["Panchagarh Sadar", "Atwari", "Boda", "Debiganj", "Tetulia"],

  Thakurgaon: [
    "Thakurgaon Sadar",
    "Baliadangi",
    "Haripur",
    "Pirganj",
    "Ranisankail",
  ],

  Lalmonirhat: [
    "Lalmonirhat Sadar",
    "Aditmari",
    "Hatibandha",
    "Kaliganj",
    "Patgram",
  ],

  Kurigram: [
    "Kurigram Sadar",
    "Bhurungamari",
    "Chilmari",
    "Nageshwari",
    "Phulbari",
    "Rajarhat",
    "Rajibpur",
    "Roumari",
    "Ulipur",
  ],

  Gaibandha: [
    "Gaibandha Sadar",
    "Gobindaganj",
    "Palashbari",
    "Phulchhari",
    "Sadullapur",
    "Saghata",
    "Sundarganj",
  ],

  Mymensingh: [
    "Mymensingh Sadar",
    "Bhaluka",
    "Dhobaura",
    "Fulbaria",
    "Gafargaon",
    "Gauripur",
    "Haluaghat",
    "Ishwarganj",
    "Muktagacha",
    "Nandail",
    "Phulpur",
    "Tara Khanda",
    "Trishal",
  ],

  Jamalpur: [
    "Jamalpur Sadar",
    "Bakshiganj",
    "Dewanganj",
    "Islampur",
    "Madarganj",
    "Melandaha",
    "Sarishabari",
  ],

  Netrokona: [
    "Netrokona Sadar",
    "Atpara",
    "Barhatta",
    "Durgapur",
    "Kalmakanda",
    "Kendua",
    "Khaliajuri",
    "Madan",
    "Mohanganj",
    "Purbadhala",
  ],

  Sherpur: ["Sherpur Sadar", "Jhenaigati", "Nakla", "Nalitabari", "Sreebardi"],
};

// Generates an array of simple { value, label } items from your districts array
export const districtsList = districts.map((district) => ({
  value: district,
  label: district,
}));
